// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/users": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "__Admin role required__\nList all users for the API.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "User created",
                        "schema": {
                            "$ref": "#/definitions/JSendSuccess-map_string_string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Non-admin user",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/JSendError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "__Admin role required__\nCreate a new user for the API. Ths user will receive an email with a token to set their password.\nYou can create users with the following roles: ` + "`" + `admin` + "`" + `, ` + "`" + `user` + "`" + `, ` + "`" + `approver` + "`" + `.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateUserQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User created",
                        "schema": {
                            "$ref": "#/definitions/JSendSuccess-map_string_string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Non-admin user",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Bad query format",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ValidationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/JSendError"
                        }
                    }
                }
            }
        },
        "/admin/users/service": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "__Admin role required__\nCreate a new service user for the API.\nYou can create users with the following roles: ` + "`" + `admin` + "`" + `, ` + "`" + `user` + "`" + `, ` + "`" + `approver` + "`" + `.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Create a new service user",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateServiceUserQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User created",
                        "schema": {
                            "$ref": "#/definitions/JSendSuccess-map_string_string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Non-admin user",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Bad query format",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ValidationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/JSendError"
                        }
                    }
                }
            }
        },
        "/sys/info": {
            "get": {
                "description": "Get information about the API including version and query limits.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Get API Info",
                "responses": {
                    "200": {
                        "description": "Response with API info",
                        "schema": {
                            "$ref": "#/definitions/JSendSuccess-InfoResp"
                        }
                    }
                }
            }
        },
        "/sys/ping": {
            "get": {
                "description": "Ping the API to check if it is alive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Ping the API",
                "responses": {
                    "200": {
                        "description": "Response with pong message",
                        "schema": {
                            "$ref": "#/definitions/JSendSuccess-PingResp"
                        }
                    }
                }
            }
        },
        "/user": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "The account will be soft deleted.\nIf the user is the last admin, the account cannot be deleted.\nIf a user is soft-deleted, the account will be permanently deleted in the future.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete user account",
                "responses": {
                    "200": {
                        "description": "Password reset",
                        "schema": {
                            "$ref": "#/definitions/JSendSuccess-map_string_string"
                        }
                    },
                    "400": {
                        "description": "Last admin account",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/JSendError"
                        }
                    }
                }
            }
        },
        "/user/email": {
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Requests an email change for the user. An email change token will be sent to the new email address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Request email change for the user",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ChangeEmailQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email change request token sent",
                        "schema": {
                            "$ref": "#/definitions/JSendSuccess-map_string_string"
                        }
                    },
                    "400": {
                        "description": "Bad request/invalid email/already in use",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Bad query format",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ValidationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/JSendError"
                        }
                    }
                }
            }
        },
        "/user/email/confirm": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Confirms an email change for the user.\nThe new email address will be active on the next login.\nYou have to login (authenticate) with the old email address to confirm the change.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Confirm email change for the user",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ConfirmEmailChangeQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email changed",
                        "schema": {
                            "$ref": "#/definitions/JSendSuccess-map_string_string"
                        }
                    },
                    "400": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Token expired",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No email change request found",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Bad query format",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ValidationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/JSendError"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Acciqures a JWT token for the user to access the API\nOnly active users can login\nUsers can downgrade their role by providing the role in the request (optional)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Login for the API to get JWT token",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/LoginQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "JWT token",
                        "schema": {
                            "$ref": "#/definitions/JSendSuccess-LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "User is not active",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Bad query format",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ValidationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/JSendError"
                        }
                    }
                }
            }
        },
        "/user/password": {
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Changes the password for the user. The old password must be provided.\nThe new password will be active on the next login.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Change password for the user",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ChangePwdQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password changed",
                        "schema": {
                            "$ref": "#/definitions/JSendSuccess-map_string_string"
                        }
                    },
                    "400": {
                        "description": "Wrong old password/invalid new password",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Bad query format",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ValidationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/JSendError"
                        }
                    }
                }
            }
        },
        "/user/password/init": {
            "post": {
                "description": "Confirms a password reset or first password set for the user.\nThe API will always return the same message (400) on auth errors to prevent email enumeration.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Confirm password reset or first password set",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ResetConfirmPwdQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password reset",
                        "schema": {
                            "$ref": "#/definitions/JSendSuccess-map_string_string"
                        }
                    },
                    "400": {
                        "description": "Bad request/invalid token",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Token expired",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Bad query format",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ValidationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/JSendError"
                        }
                    }
                }
            }
        },
        "/user/password/reset": {
            "post": {
                "description": "Requests a password reset for the user. A password reset token will be sent to the user's email.\nPassword reset tokens are valid for a limited time.\nThe API will always return the same message (200) to prevent email enumeration.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Request password reset",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ResetPwdQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password reset token sent",
                        "schema": {
                            "$ref": "#/definitions/JSendSuccess-map_string_string"
                        }
                    },
                    "422": {
                        "description": "Bad query format",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ValidationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/JSendError"
                        }
                    }
                }
            }
        },
        "/user/password/reset/confirm": {
            "post": {
                "description": "Confirms a password reset or first password set for the user.\nThe API will always return the same message (400) on auth errors to prevent email enumeration.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Confirm password reset or first password set",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ResetConfirmPwdQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password reset",
                        "schema": {
                            "$ref": "#/definitions/JSendSuccess-map_string_string"
                        }
                    },
                    "400": {
                        "description": "Bad request/invalid token",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Token expired",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Bad query format",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ValidationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/JSendError"
                        }
                    }
                }
            }
        },
        "/user/profile": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get the user profile information",
                "responses": {
                    "200": {
                        "description": "User profile",
                        "schema": {
                            "$ref": "#/definitions/JSendSuccess-UserProfile"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/JSendError"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Updates the user profile information. At least one field must be provided for update.\nThe following fields can be updated: ` + "`" + `first name` + "`" + `, ` + "`" + `last name` + "`" + `, ` + "`" + `organization` + "`" + `.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update user profile information",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateProfileQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Profile updated",
                        "schema": {
                            "$ref": "#/definitions/JSendSuccess-map_string_string"
                        }
                    },
                    "400": {
                        "description": "No changes requested or invalid data",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Bad query format",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ValidationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/JSendError"
                        }
                    }
                }
            }
        },
        "/user/refresh-token": {
            "post": {
                "description": "Refreshes the JWT token for the user to access the API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Refresh JWT token",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/RefreshQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "JWT token",
                        "schema": {
                            "$ref": "#/definitions/JSendSuccess-LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not active/role invalid/user deleted",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Bad query format",
                        "schema": {
                            "$ref": "#/definitions/JSendFailure-ValidationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/JSendError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ChangeEmailQuery": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "description": "New email address",
                    "type": "string",
                    "example": "newmail@newcomp.com"
                }
            }
        },
        "ChangePwdQuery": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "description": "New password",
                    "type": "string",
                    "example": "new_password"
                },
                "old_password": {
                    "description": "Old password",
                    "type": "string",
                    "example": "old_password"
                }
            }
        },
        "ConfirmEmailChangeQuery": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "token": {
                    "description": "Change token",
                    "type": "string",
                    "example": "my_change_token"
                }
            }
        },
        "CreateServiceUserQuery": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "organization",
                "password",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2,
                    "example": "joe@gmail.com"
                },
                "first_name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2,
                    "example": "Joe"
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2,
                    "example": "Doe"
                },
                "organization": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2,
                    "example": "ACME"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "user",
                        "approver"
                    ]
                }
            }
        },
        "CreateUserQuery": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "organization",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2,
                    "example": "joe@gmail.com"
                },
                "first_name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2,
                    "example": "Joe"
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2,
                    "example": "Doe"
                },
                "organization": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2,
                    "example": "ACME"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "user",
                        "approver"
                    ]
                }
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error message",
                    "type": "string",
                    "example": "Some error message"
                }
            }
        },
        "InfoResp": {
            "type": "object",
            "properties": {
                "meta_info": {
                    "description": "Meta",
                    "allOf": [
                        {
                            "$ref": "#/definitions/cfg.MetaConfig"
                        }
                    ]
                }
            }
        },
        "JSendError": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Error message",
                    "type": "string",
                    "example": "Internal server error"
                },
                "status": {
                    "description": "Status",
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "JSendFailure-ErrorResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data with error message(s)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    ]
                },
                "status": {
                    "description": "Status 'fail'",
                    "type": "string",
                    "example": "fail"
                }
            }
        },
        "JSendFailure-ValidationResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data with error message(s)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ValidationResponse"
                        }
                    ]
                },
                "status": {
                    "description": "Status 'fail'",
                    "type": "string",
                    "example": "fail"
                }
            }
        },
        "JSendSuccess-InfoResp": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data with success message(s)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/InfoResp"
                        }
                    ]
                },
                "status": {
                    "description": "Status 'success'",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "JSendSuccess-LoginResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data with success message(s)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/LoginResponse"
                        }
                    ]
                },
                "status": {
                    "description": "Status 'success'",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "JSendSuccess-PingResp": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data with success message(s)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/PingResp"
                        }
                    ]
                },
                "status": {
                    "description": "Status 'success'",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "JSendSuccess-UserProfile": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data with success message(s)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/UserProfile"
                        }
                    ]
                },
                "status": {
                    "description": "Status 'success'",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "JSendSuccess-map_string_string": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data with success message(s)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/map_string_string"
                        }
                    ]
                },
                "status": {
                    "description": "Status 'success'",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "LoginQuery": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "example": "joe@me.com"
                },
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "user",
                        "approver"
                    ],
                    "example": "user"
                }
            }
        },
        "LoginResponse": {
            "type": "object",
            "properties": {
                "access_expires_in": {
                    "type": "string"
                },
                "access_token": {
                    "type": "string"
                },
                "last_login": {
                    "description": "Last login time",
                    "type": "string",
                    "example": "2021-07-01T12:00:00Z"
                },
                "refresh_expires_in": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "role": {
                    "description": "User role",
                    "type": "string",
                    "example": "user"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "PingResp": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message",
                    "type": "string",
                    "example": "pong"
                }
            }
        },
        "RefreshQuery": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "my_refresh_token"
                }
            }
        },
        "ResetConfirmPwdQuery": {
            "type": "object",
            "required": [
                "email",
                "password",
                "token"
            ],
            "properties": {
                "email": {
                    "description": "Email address",
                    "type": "string",
                    "example": "joe@me.com"
                },
                "password": {
                    "description": "New password",
                    "type": "string",
                    "example": "my_new_pwd"
                },
                "token": {
                    "description": "Reset token",
                    "type": "string",
                    "example": "my_reset_token"
                }
            }
        },
        "ResetPwdQuery": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "description": "Email address",
                    "type": "string",
                    "example": "joe@me.com"
                }
            }
        },
        "UpdateProfileQuery": {
            "type": "object",
            "properties": {
                "first_name": {
                    "description": "First name",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2,
                    "example": "Joe"
                },
                "last_name": {
                    "description": "Last name",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2,
                    "example": "Doe"
                },
                "organization": {
                    "description": "Organization",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2,
                    "example": "ACME"
                }
            }
        },
        "UserProfile": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "Email address",
                    "type": "string",
                    "example": "joe@me.com"
                },
                "first_name": {
                    "description": "First name",
                    "type": "string",
                    "example": "Joe"
                },
                "last_login": {
                    "description": "Last login time",
                    "type": "string",
                    "example": "2021-07-01T12:00:00Z"
                },
                "last_name": {
                    "description": "Last name",
                    "type": "string",
                    "example": "Doe"
                },
                "organization": {
                    "description": "Organization",
                    "type": "string",
                    "example": "ACME"
                },
                "role": {
                    "description": "User role",
                    "type": "string",
                    "example": "user"
                }
            }
        },
        "ValidationResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "description": "Validation errors",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apierr.ValidationError"
                    }
                }
            }
        },
        "apierr.ValidationError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "cfg.MetaConfig": {
            "type": "object",
            "properties": {
                "api": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                },
                "version_tag": {
                    "type": "string"
                }
            }
        },
        "map_string_string": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
