services:
  mysql:
    build:
      context:    database
      dockerfile: Dockerfile
    image: safepolymed/precisiondosingdb:dev
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - TZ=Europe/Berlin