meta:
  api_name: "SafePolymed Precision Dosing API"
  api_description: "A REST-like API for SafePolymed Precision Dosing System"
  api_version: "0.1.0"
  api_url: "http://127.0.0.1:3333"
  group: "/api/v1"
server:
  read_write_timeout: "120s"
  idle_timeout: "30s"
  address: "127.0.0.1:3333"
log:
  level: "INFO" # DEBUG, INFO, WARN, ERROR
  json_format: false
  slow_query_theshold: "2s"
  db_level: "SILENT" # SILENT, INFO, WARN, ERROR
  log_caller: false # log calling site (file+line) in the log
database:
  db_name: "doseadjustservice"
  max_open_conns: 50
  max_idle_conns: 10
  max_conn_lifetime: "1h"
induvidual_db:
  max_pool_size: 50
  min_pool_size: 10
  max_idle_time: "10m"
  database: "individuals_db"
  collection: "characteristics"
auth_token:
  access_expiration_time: "8h"
  refresh_expiration_time: "24h"
  issuer: "https://doseadjustservice.clinicalpharmacy.me/"
schema:
  precheck: "file:///schemas/precheck_input.schema.json"
models:
  path: "../models"
  max_doses: 20
rlang:
  rscript_path_win: "Rscript.exe"
  rscript_path_unix: "Rscript"
  dose_adjust_script: "rscripts/mocks/test.r"
  r_worker: 4
job_runner:
  fetch_interval: "5s"
  max_concurrent_jobs: 5
  timeout: "60s"
medinfo:
  url: "https://medinfo.precisiondosing.de/api/v1"
  expiry_threshold: "2m"
mmc:
  fetch_interval: "5s"
  batch_size: 2
  expiry_threshold: "2m"
  pdf_prefix: "doseadjust"
  max_retries: 5
  production_spec: true # set to true for production auth/send specs
  mock_send: true # mock the sending of the pdf to the endpoint
  result_endpoint: "http://127.0.0.1:3333/api/v1/test/acceptresult"
  auth_endpoint: "https://safepolymed.fraunhofer.de/api/login/"
